name: week_calendar
description: A Flutter package for week_calendar functionality
version: 1.0.0
homepage: https://github.com/SoundSliced/week_calendar
repository: https://github.com/SoundSliced/week_calendar
issue_tracker: https://github.com/SoundSliced/week_calendar/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  dart_helper_utils: ^5.4.1
  s_ink_button: ^1.1.0
  icons_plus: ^5.0.0
  assorted_layout_widgets: ^11.0.0
  s_disabled: ^1.0.0
  soundsliced_dart_extensions: ^1.0.1
  calendar_date_picker2: ^2.0.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
