name: week_calendar
description: A highly customizable Flutter package that provides a horizontally scrollable weekly calendar widget with multiple visual styles and extensive configuration options.
version: 2.0.0
homepage: https://github.com/SoundSliced/week_calendar
repository: https://github.com/SoundSliced/week_calendar
issue_tracker: https://github.com/SoundSliced/week_calendar/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  s_packages: ^1.1.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true